### ISSUE TITLE
Failed to activate the coffeescript-build package

### ISSUE THREAD

**Issue by vtowntim** [iamphill/coffeescript-build#7]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.209.0
**System**: Mac OS X 10.11
**Thrown From**: [coffeescript-build](https://github.com/iamphill/coffeescript-build) package, v2.0.0

### Stack Trace

Failed to activate the coffeescript-build package

```
At Cannot read property 'prototype' of undefined

TypeError: Cannot read property 'prototype' of undefined
  at __extends (/Users/tim/.atom/packages/coffeescript-build/lib/coffeescript-build-error.coffee:4:199)
  at /Users/tim/.atom/packages/coffeescript-build/lib/coffeescript-build-error.coffee:5:3
  at Object.<anonymous> (/Users/tim/.atom/packages/coffeescript-build/lib/coffeescript-build-error.coffee:36:5)
  at Object.<anonymous> (/Users/tim/.atom/packages/coffeescript-build/lib/coffeescript-build-error.coffee:1:1)
  at Module._compile (module.js:452:26)
  at Object.requireCoffeeScript (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (/Users/tim/.atom/packages/coffeescript-build/lib/coffeescript-build-view.coffee:5:30)
  at Object.<anonymous> (/Users/tim/.atom/packages/coffeescript-build/lib/coffeescript-build-view.coffee:1:1)
  at Module._compile (module.js:452:26)
  at Object.requireCoffeeScript (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (/Users/tim/.atom/packages/coffeescript-build/lib/coffeescript-build.coffee:1:25)
  at Object.<anonymous> (/Users/tim/.atom/packages/coffeescript-build/lib/coffeescript-build.coffee:1:1)
  at Module._compile (module.js:452:26)
  at Object.requireCoffeeScript (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:709:34)
  at Package.module.exports.Package.activateConfig (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:257:12)
  at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:236:14)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:772:25
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:219:20)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at CommandPaletteView.module.exports.CommandPaletteView.confirmed (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/command-palette/lib/command-palette-view.js:159:32)
  at CommandPaletteView.module.exports.SelectListView.confirmSelection (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:338:21)
  at space-pen-div.atom.commands.add.core:confirm (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:109:19)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:238:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:520:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:355:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:177:20)

```

### Commands

```
  3x -1:39.2.0 core:move-right (atom-text-editor.editor.is-focused)
     -1:38.2.0 core:move-left (atom-text-editor.editor.is-focused)
     -1:36.6.0 core:move-right (atom-text-editor.editor.is-focused.autocomplete-active)
     -1:33.9.0 core:copy (atom-text-editor.editor.is-focused)
  4x -1:33.6.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:13.5.0 core:move-right (atom-text-editor.editor.is-focused)
     -1:13.2.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:10.8.0 core:move-left (atom-text-editor.editor.is-focused)
     -1:10.5.0 core:move-right (atom-text-editor.editor.is-focused)
     -1:10 core:move-left (atom-text-editor.editor.is-focused)
     -1:09.8.0 core:move-right (atom-text-editor.editor.is-focused)
     -0:33.1.0 editor:toggle-line-comments (atom-text-editor.editor.is-focused)
     -0:15.9.0 core:save (atom-text-editor.editor.is-focused)
     -0:03.7.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:01.2.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:01.1.0 coffeescript-build:build (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-light-ui",
      "writer-syntax"
    ],
    "disabledPackages": [
      "coffee-navigator",
      "build",
      "atom-prettify"
    ],
    "ignoredNames": [
      ".DS_Store",
      ".git"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.28.5
atom-jade, v0.3.0
build-systems, v0.5.0
coffeescript-build, v2.0.0
git-tab-status, v1.9.2
less-autocompile, v1.0.0
minimap, v4.10.0
pretty-json, v0.3.3
symbols-tree-view, v0.9.3
terminal-panel, v1.14.1
writer-syntax, v0.6.2

# Dev
No dev packages
```

**Comment by rpietro** [comment]
I'm still getting this, should it really be closed?

**Comment by objectkit** [comment]
First time trying this today, Atom showed this issue has already been noted and provided me the link to here. Got (I assume) the same stack trace...

````
Cannot read property 'prototype' of undefined
Hide Stack Trace
TypeError: Cannot read property 'prototype' of undefined
  at __extends (/Users/USER/.atom/packages/coffeescript-build/lib/coffeescript-build-error.coffee:4:199)
  at /Users/USER/.atom/packages/coffeescript-build/lib/coffeescript-build-error.coffee:5:3
  at Object.<anonymous> (/Users/USER/.atom/packages/coffeescript-build/lib/coffeescript-build-error.coffee:36:5)
  at Object.<anonymous> (/Users/USER/.atom/packages/coffeescript-build/lib/coffeescript-build-error.coffee:1:1)
  at Module._compile (module.js:428:26)
  at Object.defineProperty.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:169:21)
  at Module.load (module.js:353:32)
  at Function.Module._load (module.js:308:12)
  at Module.require (module.js:363:17)
  at require (module.js:382:17)
  at Object.<anonymous> (/Users/USER/.atom/packages/coffeescript-build/lib/coffeescript-build-view.coffee:5:30)
  at Object.<anonymous> (/Users/USER/.atom/packages/coffeescript-build/lib/coffeescript-build-view.coffee:1:1)
  at Module._compile (module.js:428:26)
  at Object.defineProperty.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:169:21)
  at Module.load (module.js:353:32)
  at Function.Module._load (module.js:308:12)
  at Module.require (module.js:363:17)
  at require (module.js:382:17)
  at Object.<anonymous> (/Users/USER/.atom/packages/coffeescript-build/lib/coffeescript-build.coffee:1:25)
  at Object.<anonymous> (/Users/USER/.atom/packages/coffeescript-build/lib/coffeescript-build.coffee:1:1)
  at Module._compile (module.js:428:26)
  at Object.defineProperty.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:169:21)
  at Module.load (module.js:353:32)
  at Function.Module._load (module.js:308:12)
  at Module.require (module.js:363:17)
  at require (module.js:382:17)
  at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:761:34)
  at Package.module.exports.Package.activateConfig (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:263:14)
  at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:241:14)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:838:25
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:226:20)
  at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:145:19)
  at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:70:30)
  at emitOne (events.js:77:13)
  at EventEmitter.emit (events.js:169:7)
````
